theme: jekyll-theme-cayman
title: 年轻的比克                     #你博客的标题
SEOTitle: 年轻的比克     #显示在浏览器上搜索的时候显示的标题
header-img: img/bike.jpeg     #显示在首页的背景图片
email: mtry000@gmail.com    
description: "就是想做点什么"              #网站介绍
keyword: "比克的博客" #关键词